%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with error message "Found incompatible YAML document."
# -*- coding: UTF-8, tab-width: 4 -*-
---

name: 'Build NodeMCU'
description: 'Build a NodeMCU firmware image.'

inputs:
    under_score:
        description: 'A dummy input with _ in its name'
        required: false
        default: '_'
    hyphen-minus:
        description: 'A dummy input with - in its name'
        required: false
        default: '-'

runs:
    using: 'docker'
    image: 'Dockerfile'
    args: []











...
